//
// Created by shenrique on 10/3/22.
//

#ifndef WIFI_CONNECT_STRMAP_H
#define WIFI_CONNECT_STRMAP_H

#define o false
#define X true

std::array<std::array<std::array<bool, 8>, 8>, 128> strMap = {
// char = ( )
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = )
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (	)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (\n)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (\t)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ( )
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (!)
        o, o, o, X, X, o, o, o,
        o, o, X, X, X, X, o, o,
        o, o, X, X, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (")
        o, X, X, o, X, X, o, o,
        o, X, X, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (#)
        o, X, X, o, X, X, o, o,
        o, X, X, o, X, X, o, o,
        X, X, X, X, X, X, X, o,
        o, X, X, o, X, X, o, o,
        X, X, X, X, X, X, X, o,
        o, X, X, o, X, X, o, o,
        o, X, X, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = ($)
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, X, o, o,
        X, X, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        X, X, X, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (%)
        o, o, o, o, o, o, o, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (&)
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, X, X, X, o, X, X, o,
        X, X, o, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (')
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (()
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ())
        o, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (*)
        o, o, o, o, o, o, o, o,
        o, X, X, o, o, X, X, o,
        o, o, X, X, X, X, o, o,
        X, X, X, X, X, X, X, X,
        o, o, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (+)
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        X, X, X, X, X, X, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (,)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
// char = (-)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (.)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (/)
        o, o, o, o, o, X, X, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        X, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (0)
        o, X, X, X, X, X, o, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, X, X, X, o,
        X, X, o, X, X, X, X, o,
        X, X, X, X, o, X, X, o,
        X, X, X, o, o, X, X, o,
        o, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (1)
        o, o, X, X, o, o, o, o,
        o, X, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (2)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (3)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (4)
        o, o, o, X, X, X, o, o,
        o, o, X, X, X, X, o, o,
        o, X, X, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, X, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (5)
        X, X, X, X, X, X, o, o,
        X, X, o, o, o, o, o, o,
        X, X, X, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (6)
        o, o, X, X, X, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        X, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (7)
        X, X, X, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (8)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (9)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, X, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (:)
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (;)
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
// char = (<)
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (=)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (>)
        o, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (?)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (@)
        o, X, X, X, X, X, o, o,
        X, X, o, o, o, X, X, o,
        X, X, o, X, X, X, X, o,
        X, X, o, X, X, X, X, o,
        X, X, o, X, X, X, X, o,
        X, X, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (A)
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (B)
        X, X, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (C)
        o, o, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        X, X, o, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        o, X, X, o, o, X, X, o,
        o, o, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (D)
        X, X, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        X, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (E)
        X, X, X, X, X, X, X, o,
        o, X, X, o, o, o, X, o,
        o, X, X, o, X, o, o, o,
        o, X, X, X, X, o, o, o,
        o, X, X, o, X, o, o, o,
        o, X, X, o, o, o, X, o,
        X, X, X, X, X, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (F)
        X, X, X, X, X, X, X, o,
        o, X, X, o, o, o, X, o,
        o, X, X, o, X, o, o, o,
        o, X, X, X, X, o, o, o,
        o, X, X, o, X, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (G)
        o, o, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        X, X, o, o, o, o, o, o,
        X, X, o, o, o, o, o, o,
        X, X, o, o, X, X, X, o,
        o, X, X, o, o, X, X, o,
        o, o, X, X, X, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (H)
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (I)
        o, X, X, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (J)
        o, o, o, X, X, X, X, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (K)
        X, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        o, X, X, o, o, X, X, o,
        X, X, X, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (L)
        X, X, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, X, o,
        o, X, X, o, o, X, X, o,
        X, X, X, X, X, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (M)
        X, X, o, o, o, X, X, o,
        X, X, X, o, X, X, X, o,
        X, X, X, X, X, X, X, o,
        X, X, X, X, X, X, X, o,
        X, X, o, X, o, X, X, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (N)
        X, X, o, o, o, X, X, o,
        X, X, X, o, o, X, X, o,
        X, X, X, X, o, X, X, o,
        X, X, o, X, X, X, X, o,
        X, X, o, o, X, X, X, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (O)
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (P)
        X, X, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, X, X, X, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (Q)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, X, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (R)
        X, X, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, X, X, X, o, o,
        o, X, X, o, X, X, o, o,
        o, X, X, o, o, X, X, o,
        X, X, X, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (S)
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, o, o, o, o, o,
        o, X, X, X, o, o, o, o,
        o, o, o, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (T)
        X, X, X, X, X, X, o, o,
        X, o, X, X, o, X, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (U)
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (V)
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (W)
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        X, X, o, X, o, X, X, o,
        X, X, X, X, X, X, X, o,
        X, X, X, o, X, X, X, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (X)
        X, X, o, o, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (Y)
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (Z)
        X, X, X, X, X, X, X, o,
        X, X, o, o, o, X, X, o,
        X, o, o, o, X, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, X, X, o, o, X, o,
        o, X, X, o, o, X, X, o,
        X, X, X, X, X, X, X, o,
        o, o, o, o, o, o, o, o,
// char = ([)
        o, X, X, X, X, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (\)
        X, X, o, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, o, X, X, o,
        o, o, o, o, o, o, X, o,
        o, o, o, o, o, o, o, o,
// char = (])
        o, X, X, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (^)
        o, o, o, X, o, o, o, o,
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (_)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, X, X, X,
// char = (`)
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (a)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (b)
        X, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        X, X, o, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (c)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (d)
        o, o, o, X, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (e)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, o, o,
        X, X, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (f)
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (g)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, o, X, X, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        o, o, o, o, X, X, o, o,
        X, X, X, X, X, o, o, o,
// char = (h)
        X, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        X, X, X, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (i)
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (j)
        o, o, o, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
// char = (k)
        X, X, X, o, o, o, o, o,
        o, X, X, o, o, o, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        X, X, X, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (l)
        o, X, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (m)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, X, X, X, X, X, o,
        X, X, X, X, X, X, X, o,
        X, X, o, X, o, X, X, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (n)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (o)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (p)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, X, X, X, o, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, X, X, X, o, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
// char = (q)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, o, X, X, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        o, o, o, o, X, X, o, o,
        o, o, o, X, X, X, X, o,
// char = (r)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, X, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, X, X, o, o, X, X, o,
        o, X, X, o, o, o, o, o,
        X, X, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (s)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, X, X, X, X, X, o, o,
        X, X, o, o, o, o, o, o,
        o, X, X, X, X, o, o, o,
        o, o, o, o, X, X, o, o,
        X, X, X, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (t)
        o, o, o, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, X, X, X, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, X, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (u)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (v)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (w)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, o, X, X, o,
        X, X, o, X, o, X, X, o,
        X, X, X, X, X, X, X, o,
        X, X, X, X, X, X, X, o,
        o, X, X, o, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (x)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, o, X, X, o,
        o, X, X, o, X, X, o, o,
        o, o, X, X, X, o, o, o,
        o, X, X, o, X, X, o, o,
        X, X, o, o, o, X, X, o,
        o, o, o, o, o, o, o, o,
// char = (y)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        X, X, o, o, X, X, o, o,
        o, X, X, X, X, X, o, o,
        o, o, o, o, X, X, o, o,
        X, X, X, X, X, o, o, o,
// char = (z)
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        X, X, X, X, X, X, o, o,
        X, o, o, X, X, o, o, o,
        o, o, X, X, o, o, o, o,
        o, X, X, o, o, X, o, o,
        X, X, X, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = ({)
        o, o, o, X, X, X, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        X, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
// char = (|)
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, X, X, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (})
        X, X, X, o, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        o, o, o, X, X, X, o, o,
        o, o, X, X, o, o, o, o,
        o, o, X, X, o, o, o, o,
        X, X, X, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = (~)
        o, X, X, X, o, X, X, o,
        X, X, o, X, X, X, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
// char = ()
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
        o, o, o, o, o, o, o, o,
};

#undef o
#undef X


#endif //WIFI_CONNECT_STRMAP_H
